"""INBOX.md writer and parser utilities."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, timedelta
from pathlib import Path
import re

from .hunter import top_contact_summaries
from .identity import JobKey, key_from_args
from .paths import company_dirname


@dataclass(frozen=True)
class InboxRow:
    """A row to write to INBOX.md."""

    title: str
    company: str
    slug: str
    score: int | None = None
    url: str | None = None
    status: str = "[ ]"  # [ ] = active, [x] = submitted, [~] = skipped


@dataclass(frozen=True)
class AppliedInboxRow:
    """A submitted application block to write under the Applied section."""

    title: str
    company: str
    archive_slug: str
    applied_on: str
    url: str | None = None
    best_contact: str | None = None
    top_contacts: tuple[str, ...] = ()


@dataclass(frozen=True)
class InboxItem:
    """A parsed row from INBOX.md."""

    slug: str
    status: str  # "[ ]", "[x]", or "[~]"
    title: str
    company: str
    score: int | None = None
    job_path: Path | None = None
    cv_path: Path | None = None
    cover_path: Path | None = None
    apply_url: str | None = None
    source: str | None = None
    job_id: str | None = None

    @property
    def key(self) -> JobKey:
        """BoardKey when Apply URL yielded source+id, else ManualKey."""
        return key_from_args(self.source, self.job_id, self.company, self.title)


# Map from URL host substring to (source label, job-id regex).
# Tracker rows are written with these same source labels by the scrapers,
# so extracting them here lets BoardKey match the tracker row during reconcile.
_URL_SOURCES: tuple[tuple[str, str, str], ...] = (
    ("seek.com", "seek", r"/job/(\d+)"),
    ("linkedin.com", "linkedin", r"/jobs/view/(\d+)"),
    ("hiring.cafe", "hiringcafe", r"/(?:viewjob|job)/([A-Za-z0-9]+)"),
    ("workingnomads.com", "workingnomads", r"/jobs/([^/?#]+)"),
    ("wellfound.com", "wellfound", r"/jobs/(\d+)"),
    ("weworkremotely.com", "weworkremotely", r"/remote-jobs/([^/?#]+)"),
    ("prosple.com", "prosple", r"/jobs-internships/([^/?#]+)"),
)


def _parse_apply_url(url: str | None) -> tuple[str | None, str | None]:
    """Return (source, job_id) from a known job-board URL, or (None, None)."""
    if not url:
        return None, None
    for host, source, id_pattern in _URL_SOURCES:
        if host in url:
            m = re.search(id_pattern, url)
            return source, (m.group(1) if m else None)
    return None, None


def _linked_doc_path(line: str, label: str, slug: str) -> Path | None:
    """Resolve a ``[label](./relative)`` INBOX link to its active-dir path."""
    match = re.search(rf"\[{re.escape(label)}\]\(\.*/([^)]+?)\)", line)
    if not match:
        return None
    return Path(f"applications/active/{slug}/{match.group(1)}")


_INBOX_PATTERN = re.compile(
    r"""^-\s+\[(?P<status>[ x~])\]\s*\*\*(?P<title>[^*]+)\s*\*\*\s*@\s*(?P<company>[^(]+)(?:\s*\(score:\s*(?P<score>\d+)\))?""",
    re.MULTILINE,
)


def parse_inbox(inbox_path: Path) -> list[InboxItem]:
    """Extract structured items from INBOX.md checkbox list."""
    if not inbox_path.exists():
        return []

    text = inbox_path.read_text()
    items: list[InboxItem] = []

    for line in text.splitlines():
        match = _INBOX_PATTERN.search(line)
        if not match:
            continue

        status_raw = match.group("status")
        status = {
            " ": "[ ]",
            "x": "[x]",
            "~": "[~]",
        }.get(status_raw, "[ ]")

        title = match.group("title").strip()
        company = match.group("company").strip()
        score_str = match.group("score")
        score = int(score_str) if score_str else None

        url_match = re.search(r"\[Apply\s*↗\]\((https?://[^)]+)\)", line)
        apply_url = url_match.group(1) if url_match else None
        source, job_id = _parse_apply_url(apply_url)

        # Slug = the on-disk active dir name. Derived from company + job_id so
        # the same company applied for twice (different listings) doesn't
        # collide. Matches company_dirname used by workflow.create_application_package.
        slug = company_dirname(company, job_id)

        job_path = _linked_doc_path(line, "JD", slug)
        cv_path = _linked_doc_path(line, "CV", slug)
        cover_path = _linked_doc_path(line, "Letter", slug)

        items.append(
            InboxItem(
                slug=slug,
                status=status,
                title=title,
                company=company,
                score=score,
                job_path=job_path,
                cv_path=cv_path,
                cover_path=cover_path,
                apply_url=apply_url,
                source=source,
                job_id=job_id,
            )
        )

    return items


_CHECKLIST_RE = re.compile(r"^-\s+\[[ x~]\]\s")
_DEFAULT_PREAMBLE = [
    "<!-- This file is auto-generated by the job research pipeline. -->",
    "",
    "<!-- In To Apply: [ ] = active, [x] = submitted, [~] = not interested -->",
]
_TO_APPLY_HEADING = "## To Apply"
_APPLIED_HEADING = "## Applied"
_COLD_EMAIL_TEMPLATE_LINK = "../templates/cold-email.md"


def format_row(row: InboxRow) -> str:
    """Format an InboxRow as a markdown checklist item."""
    parts = [
        f"- {row.status} **{row.title}** @ {row.company}",
    ]

    if row.score is not None:
        parts.append(f" (score: {row.score})")

    links = []
    links.append(f"[JD](./active/{row.slug}/research/job-description.md)")
    links.append(f"[CV](./active/{row.slug}/documents/resume.pdf)")
    links.append(f"[Letter](./active/{row.slug}/documents/cover-letter.md)")

    if row.url:
        links.append(f"[Apply ↗]({row.url})")

    parts.append(" · ")
    parts.append(" · ".join(links))

    return "".join(parts)


def format_applied_row(row: AppliedInboxRow) -> str:
    """Format an applied application block with outreach follow-up tasks."""
    applied = date.fromisoformat(row.applied_on)
    follow_up = (applied + timedelta(days=7)).isoformat()

    links = [
        f"[JD](./archive/submitted/{row.archive_slug}/research/job-description.md)",
        f"[CV](./archive/submitted/{row.archive_slug}/documents/resume.pdf)",
        f"[Letter](./archive/submitted/{row.archive_slug}/documents/cover-letter.md)",
        f"[Cold Email](./archive/submitted/{row.archive_slug}/documents/cold-email.md)",
    ]
    if row.url:
        links.append(f"[Apply ↗]({row.url})")

    lines = [
        f"- **{row.title}** @ {row.company} — applied {row.applied_on} · "
        + " · ".join(links)
    ]
    top_contacts = row.top_contacts or (() if not row.best_contact else (row.best_contact,))
    if top_contacts:
        lines.append("  - Top contacts:")
        for idx, contact in enumerate(top_contacts, start=1):
            lines.append(f"    {idx}. {contact}")
    lines.append(
        f"  - [ ] Cold email sent: {row.applied_on} → follow up on: {follow_up} · [Template]({_COLD_EMAIL_TEMPLATE_LINK})"
    )
    return "\n".join(lines)


def _split_inbox_sections(text: str) -> tuple[list[str], list[str], list[str]]:
    """Return (preamble, to_apply_lines, applied_lines), migrating old layout."""
    lines = text.splitlines()
    if not lines:
        return _DEFAULT_PREAMBLE[:], [], []

    preamble: list[str] = []
    to_apply: list[str] = []
    applied: list[str] = []
    section: str | None = None

    for line in lines:
        if line == "# Job INBOX":
            continue
        if line == _TO_APPLY_HEADING:
            section = "to_apply"
            continue
        if line == _APPLIED_HEADING:
            section = "applied"
            continue

        if section == "to_apply":
            to_apply.append(line)
        elif section == "applied":
            applied.append(line)
        else:
            preamble.append(line)

    if _TO_APPLY_HEADING not in lines and _APPLIED_HEADING not in lines:
        migrated_to_apply = [line for line in preamble if _CHECKLIST_RE.match(line)]
        migrated_preamble = [line for line in preamble if not _CHECKLIST_RE.match(line)]
        preamble = migrated_preamble
        to_apply = migrated_to_apply

    while preamble and not preamble[0].strip():
        preamble.pop(0)
    while preamble and not preamble[-1].strip():
        preamble.pop()

    if not preamble:
        preamble = _DEFAULT_PREAMBLE[:]

    return preamble, to_apply, applied


def _render_inbox(preamble: list[str], to_apply: list[str], applied: list[str]) -> str:
    """Render the canonical INBOX.md structure."""
    lines = ["# Job INBOX", ""]
    lines.extend(preamble)
    if lines[-1] != "":
        lines.append("")
    lines.extend([_TO_APPLY_HEADING, ""])

    trimmed_to_apply = to_apply[:]
    while trimmed_to_apply and not trimmed_to_apply[0].strip():
        trimmed_to_apply.pop(0)
    while trimmed_to_apply and not trimmed_to_apply[-1].strip():
        trimmed_to_apply.pop()
    lines.extend(trimmed_to_apply)
    lines.extend(["", _APPLIED_HEADING, ""])

    trimmed_applied = applied[:]
    while trimmed_applied and not trimmed_applied[0].strip():
        trimmed_applied.pop(0)
    while trimmed_applied and not trimmed_applied[-1].strip():
        trimmed_applied.pop()
    lines.extend(trimmed_applied)

    return "\n".join(lines).rstrip() + "\n"


def _load_sections(inbox_path: Path) -> tuple[list[str], list[str], list[str]]:
    """Load and normalize the INBOX sections."""
    if not inbox_path.exists():
        return _DEFAULT_PREAMBLE[:], [], []
    return _split_inbox_sections(inbox_path.read_text())


def write_inbox_row(inbox_path: Path, row: InboxRow) -> None:
    """Append a row to the To Apply section, creating the file if needed."""
    inbox_path.parent.mkdir(parents=True, exist_ok=True)
    preamble, to_apply, applied = _load_sections(inbox_path)

    line = format_row(row)
    marker = f"**{row.title}** @ {row.company}"
    if any(marker in existing_line for existing_line in to_apply):
        return

    to_apply.append(line)
    inbox_path.write_text(_render_inbox(preamble, to_apply, applied))


def write_applied_row(inbox_path: Path, row: AppliedInboxRow) -> None:
    """Append a submitted application block to the Applied section."""
    inbox_path.parent.mkdir(parents=True, exist_ok=True)
    preamble, to_apply, applied = _load_sections(inbox_path)

    top_contacts = row.top_contacts
    if not top_contacts:
        archive_dir = inbox_path.parent / "archive" / "submitted" / row.archive_slug
        discovered = tuple(top_contact_summaries(archive_dir, limit=3))
        best_contact = discovered[0] if discovered else row.best_contact
        row = AppliedInboxRow(
            title=row.title,
            company=row.company,
            archive_slug=row.archive_slug,
            applied_on=row.applied_on,
            url=row.url,
            best_contact=best_contact,
            top_contacts=discovered,
        )

    block = format_applied_row(row)
    marker = f"./archive/submitted/{row.archive_slug}/research/job-description.md"
    if any(marker in existing_line for existing_line in applied):
        return

    if applied and applied[-1].strip():
        applied.append("")
    applied.extend(block.splitlines())
    inbox_path.write_text(_render_inbox(preamble, to_apply, applied))


def write_inbox_rows(inbox_path: Path, rows: list[InboxRow]) -> None:
    """Append multiple rows to the To Apply section."""
    for row in rows:
        write_inbox_row(inbox_path, row)


def clear_inbox(inbox_path: Path) -> None:
    """Clear all rows from INBOX.md and preserve the section scaffold."""
    inbox_path.parent.mkdir(parents=True, exist_ok=True)
    inbox_path.write_text(_render_inbox(_DEFAULT_PREAMBLE[:], [], []))
