"""INBOX.md writer utilities."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, timedelta
from pathlib import Path
import re

from .hunter import top_contact_summaries


@dataclass(frozen=True)
class InboxRow:
    """A row to write to INBOX.md."""

    title: str
    company: str
    slug: str
    score: int | None = None
    url: str | None = None
    status: str = "[ ]"  # [ ] = active, [x] = submitted, [~] = skipped


@dataclass(frozen=True)
class AppliedInboxRow:
    """A submitted application block to write under the Applied section."""

    title: str
    company: str
    archive_slug: str
    applied_on: str
    url: str | None = None
    best_contact: str | None = None
    top_contacts: tuple[str, ...] = ()


_CHECKLIST_RE = re.compile(r"^-\s+\[[ x~]\]\s")
_DEFAULT_PREAMBLE = [
    "<!-- This file is auto-generated by the job research pipeline. -->",
    "",
    "<!-- In To Apply: [ ] = active, [x] = submitted, [~] = not interested -->",
]
_TO_APPLY_HEADING = "## To Apply"
_APPLIED_HEADING = "## Applied"
_COLD_EMAIL_TEMPLATE_LINK = "../templates/cold-email.md"


def format_row(row: InboxRow) -> str:
    """Format an InboxRow as a markdown checklist item."""
    parts = [
        f"- {row.status} **{row.title}** @ {row.company}",
    ]

    if row.score is not None:
        parts.append(f" (score: {row.score})")

    links = []
    links.append(f"[JD](./active/{row.slug}/research/job-description.md)")
    links.append(f"[CV](./active/{row.slug}/documents/resume.pdf)")
    links.append(f"[Letter](./active/{row.slug}/documents/cover-letter.md)")

    if row.url:
        links.append(f"[Apply ↗]({row.url})")

    parts.append(" · ")
    parts.append(" · ".join(links))

    return "".join(parts)


def format_applied_row(row: AppliedInboxRow) -> str:
    """Format an applied application block with outreach follow-up tasks."""
    applied = date.fromisoformat(row.applied_on)
    follow_up = (applied + timedelta(days=7)).isoformat()

    links = [
        f"[JD](./archive/submitted/{row.archive_slug}/research/job-description.md)",
        f"[CV](./archive/submitted/{row.archive_slug}/documents/resume.pdf)",
        f"[Letter](./archive/submitted/{row.archive_slug}/documents/cover-letter.md)",
        f"[Cold Email](./archive/submitted/{row.archive_slug}/documents/cold-email.md)",
    ]
    if row.url:
        links.append(f"[Apply ↗]({row.url})")

    lines = [
        f"- **{row.title}** @ {row.company} — applied {row.applied_on} · "
        + " · ".join(links)
    ]
    top_contacts = row.top_contacts or (() if not row.best_contact else (row.best_contact,))
    if top_contacts:
        lines.append("  - Top contacts:")
        for idx, contact in enumerate(top_contacts, start=1):
            lines.append(f"    {idx}. {contact}")
    lines.append(
        f"  - [ ] Cold email sent: {row.applied_on} → follow up on: {follow_up} · [Template]({_COLD_EMAIL_TEMPLATE_LINK})"
    )
    return "\n".join(lines)


def _split_inbox_sections(text: str) -> tuple[list[str], list[str], list[str]]:
    """Return (preamble, to_apply_lines, applied_lines), migrating old layout."""
    lines = text.splitlines()
    if not lines:
        return _DEFAULT_PREAMBLE[:], [], []

    preamble: list[str] = []
    to_apply: list[str] = []
    applied: list[str] = []
    section: str | None = None

    for line in lines:
        if line == "# Job INBOX":
            continue
        if line == _TO_APPLY_HEADING:
            section = "to_apply"
            continue
        if line == _APPLIED_HEADING:
            section = "applied"
            continue

        if section == "to_apply":
            to_apply.append(line)
        elif section == "applied":
            applied.append(line)
        else:
            preamble.append(line)

    if _TO_APPLY_HEADING not in lines and _APPLIED_HEADING not in lines:
        migrated_to_apply = [line for line in preamble if _CHECKLIST_RE.match(line)]
        migrated_preamble = [line for line in preamble if not _CHECKLIST_RE.match(line)]
        preamble = migrated_preamble
        to_apply = migrated_to_apply

    while preamble and not preamble[0].strip():
        preamble.pop(0)
    while preamble and not preamble[-1].strip():
        preamble.pop()

    if not preamble:
        preamble = _DEFAULT_PREAMBLE[:]

    return preamble, to_apply, applied


def _render_inbox(preamble: list[str], to_apply: list[str], applied: list[str]) -> str:
    """Render the canonical INBOX.md structure."""
    lines = ["# Job INBOX", ""]
    lines.extend(preamble)
    if lines[-1] != "":
        lines.append("")
    lines.extend([_TO_APPLY_HEADING, ""])

    trimmed_to_apply = to_apply[:]
    while trimmed_to_apply and not trimmed_to_apply[0].strip():
        trimmed_to_apply.pop(0)
    while trimmed_to_apply and not trimmed_to_apply[-1].strip():
        trimmed_to_apply.pop()
    lines.extend(trimmed_to_apply)
    lines.extend(["", _APPLIED_HEADING, ""])

    trimmed_applied = applied[:]
    while trimmed_applied and not trimmed_applied[0].strip():
        trimmed_applied.pop(0)
    while trimmed_applied and not trimmed_applied[-1].strip():
        trimmed_applied.pop()
    lines.extend(trimmed_applied)

    return "\n".join(lines).rstrip() + "\n"


def _load_sections(inbox_path: Path) -> tuple[list[str], list[str], list[str]]:
    """Load and normalize the INBOX sections."""
    if not inbox_path.exists():
        return _DEFAULT_PREAMBLE[:], [], []
    return _split_inbox_sections(inbox_path.read_text())


def write_inbox_row(inbox_path: Path, row: InboxRow) -> None:
    """Append a row to the To Apply section, creating the file if needed."""
    inbox_path.parent.mkdir(parents=True, exist_ok=True)
    preamble, to_apply, applied = _load_sections(inbox_path)

    line = format_row(row)
    marker = f"**{row.title}** @ {row.company}"
    if any(marker in existing_line for existing_line in to_apply):
        return

    to_apply.append(line)
    inbox_path.write_text(_render_inbox(preamble, to_apply, applied))


def write_applied_row(inbox_path: Path, row: AppliedInboxRow) -> None:
    """Append a submitted application block to the Applied section."""
    inbox_path.parent.mkdir(parents=True, exist_ok=True)
    preamble, to_apply, applied = _load_sections(inbox_path)

    top_contacts = row.top_contacts
    if not top_contacts:
        archive_dir = inbox_path.parent / "archive" / "submitted" / row.archive_slug
        discovered = tuple(top_contact_summaries(archive_dir, limit=3))
        best_contact = discovered[0] if discovered else row.best_contact
        row = AppliedInboxRow(
            title=row.title,
            company=row.company,
            archive_slug=row.archive_slug,
            applied_on=row.applied_on,
            url=row.url,
            best_contact=best_contact,
            top_contacts=discovered,
        )

    block = format_applied_row(row)
    marker = f"./archive/submitted/{row.archive_slug}/research/job-description.md"
    if any(marker in existing_line for existing_line in applied):
        return

    if applied and applied[-1].strip():
        applied.append("")
    applied.extend(block.splitlines())
    inbox_path.write_text(_render_inbox(preamble, to_apply, applied))


def write_inbox_rows(inbox_path: Path, rows: list[InboxRow]) -> None:
    """Append multiple rows to the To Apply section."""
    for row in rows:
        write_inbox_row(inbox_path, row)


def clear_inbox(inbox_path: Path) -> None:
    """Clear all rows from INBOX.md and preserve the section scaffold."""
    inbox_path.parent.mkdir(parents=True, exist_ok=True)
    inbox_path.write_text(_render_inbox(_DEFAULT_PREAMBLE[:], [], []))
